### ISSUE TITLE
Allow compilation of Static libRed

### ISSUE THREAD

**Issue by cup** [red/REP#46]
Currently you can build a Shared libRed like so:

~~~
red build libRed
~~~

however it appears Red has no option to build a Static libRed.

**Comment by cup** [comment]
https://github.com/red/red/issues/3417

**Comment by greggirwin** [comment]
@cup that's correct. It's not on our roadmap, so I'll close this ticket for now.

**Comment by cup** [comment]
@greggirwin and this is exactly why I waited this long to post this. Its funny, you yourself said this:

> Thanks for the ticket. We've set up https://github.com/red/rep/issues specifically for wish tickets like this. If you could add your wish over there, that would be great.

at least my suspicions then are now confirmed.

**Comment by 89z** [comment]
https://github.com/red/red/issues/3412

**Comment by 89z** [comment]
I agree with original poster, kind of strange not to offer static compile, as its offered by every major programming language today, such as Go, Nim, Rust. Anyone who prefers a static workflow has to wait 30 second every single time they compile anything.

**Comment by greggirwin** [comment]
@89z, please stop trolling. You just did this on HN and were called out for it. You *know* your argument is incorrect and specious, and cherry-picking data points won't change that.

**Comment by 89z** [comment]
@greggirwin not sure how you managed to delude yourself, but static compilation is an objectively important factor in a programming language.

**Comment by 89z** [comment]
Sanity check for myself:

~~~
PS C:\> cat main.go
package main
import "fmt"

func main() {
   fmt.Println("hello world")
}

PS C:\> Measure-Command { go build main.go }
Milliseconds      : 177
~~~

thats how it should be for static build, not 30 seconds.

**Comment by 89z** [comment]
(reposting deleted comment) sanity check for myself:

~~~
PS C:\> cat main.go
package main
import "fmt"

func main() {
   fmt.Println("hello world")
}

PS C:\> Measure-Command { go build main.go }
Milliseconds      : 177
~~~

thats how it should be for static build, not 30 seconds. This is not a troll, this is a valid comparison with a popular programming language. Every language has strengths and weaknesses. I am not too familiar with Red, but I think its strength is that its simple to get up and running, and its easy to do command line or even GUI programs in Red.

However one of Red weakness, is its awful in regard to compilation time, because developers made the decision to recompile the runtime every time. I get no one like critcism, but to actively censor any negative comments is pretty sad.

**Comment by 89z** [comment]
Sanity check for myself:

~~~
PS C:\> cat main.go
package main
import "fmt"

func main() {
   fmt.Println("hello world")
}

PS C:\> Measure-Command { go build main.go }
Milliseconds      : 177
~~~

thats how it should be for static build, not 30 seconds. This is not a troll, this is a valid comparison with a popular programming language. Every language has strengths and weaknesses. I am not too familiar with Red, but I think its strength is that its simple to get up and running, and its easy to do command line or even GUI programs in Red.

However one of Red weakness, is its awful in regard to compilation time, because developers made the decision to recompile the runtime every time. I get no one like critcism, but to actively censor any negative comments is pretty sad.

**Comment by greggirwin** [comment]
Steven, as long as you keep posting the same message, I'm going to keep deleting it. Become a civil and helpful member of our community, provide constructive feedback, and we can build a working relationship from there.
